
persistence:
  mongo:
    cluster: localhost
    user: muchor
    db: muchor
    pwd: passwd
    
    
channel:
  MNMN:
    FooShopMNMN:
      endpoint: http://login:password@ws.monechelle-test.com
      login: mon_login
      password: mon_password
        

jobs:
  manomano-order-import-FooShopMNMN:
    class: manomano.job.ImportOrders
    schedule:
      second: "*/30"
      minute: "*"
      hour: "*"
    params:
      channelInstance: FooShopMNMN
      shippingCostChargeKey: SHIP
      shippingCostChargeName: Shipping costs


---

config: production

channel:
  MNMN:
    FooShopMNMN:
      endpoint: http://ws.monechelle.com