
persistence:
  mongo:
    cluster: localhost
    user: muchor
    db: muchor
    pwd: passwd
    
    
channel:
  MNMN:
    FooShopMNMN:
      endpoint: http://login:password@ws.monechelle-test.com
      login: mon_login
      password: mon_password
        

jobs:
  
  manomano-attribute-import:
    class: manomano.job.AttributeImport
    runAtStartup: true
    schedule:
      minute: 5
      hour: 4
      day: 1
#      month: 8
#      year: 2018
  
  manomano-order-import-FooShopMNMN:
    class: manomano.job.ImportOrders
    schedule:
      second: "*/30"
      minute: "*"
      hour: "*"
    params:
      channelInstance: FooShopMNMN
      shippingCostChargeName: Shipping costs
  
  manomano-article-feed-FooShopMNMN:
    class: manomano.job.ArticleFeedGenerator
    schedule:
      second: "*/30"
      minute: "*"
      hour: "*"
    params:
      channelInstance: FooShopMNMN
      languageCode: de
      fileName: ManoMano.csv
      target:
        protocol: file
        directory: /tmp

---

config: production

channel:
  MNMN:
    FooShopMNMN:
      endpoint: http://ws.monechelle.com