
persistence:
  mongo:
    cluster: localhost
    db: muchor
    user: muchor
    pwd: passwd
  eclipselink:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/muchor?useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&useUnicode=yes&characterEncoding=UTF-8
    user: root
    password: Hallo
    loggingLevel: WARNING
#    ddlGeneration: none
    ddlGeneration: drop-and-create-tables
    
jobs:
  test:
    class: de.websplatter.muchor.example.filler.Test
    runAtStartup: true
    schedule:
      minute: "22"
      hour: "22"
